insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Miniature Sports Games', 'Fun tabletop air hockey for home or office.', 5, 3, '1/1/2025');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Athletic Footwear', 'Versatile canvas sneakers suitable for everyday wear with a comfortable fit.', 5, 24, '3/18/2025');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Garden Tools', 'All-in-one tool for measuring soil moisture, light, and pH.', 2, 30, '12/8/2024');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Granola/Cereal', 'Crunchy granola with oats, almonds, and dried cranberries.', 2, 3, '1/7/2025');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Cooking Appliances', 'Stackable steamers for healthy cooking of vegetables and seafood.', 5, 4, '12/25/2024');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Fitness & Nutrition', 'Nutritious protein bars for on-the-go snacking.', 3, 8, '7/4/2024');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Healthy Snacks', 'A pack of assorted nut and protein bars for a quick energy boost.', 5, 36, '9/6/2024');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Healthy Snacks', 'Crispy and crunchy snack made from assorted vegetables.', 4, 17, '9/3/2024');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Healthy Snacks', 'Ready-to-eat chia seed pudding made with coconut milk, perfect for breakfast or dessert.', 1, 11, '4/18/2025');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Fishing Equipment', 'Organized tackle box for fishing gear.', 2, 10, '10/18/2024');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Storage Devices', '32GB USB flash drive with fast data transfer speeds.', 3, 24, '8/22/2024');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Baking Accessories', 'Durable baking sheet coated for easy food release.', 4, 8, '12/21/2024');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Soups & Broths', 'Flavorful lentil soup, perfect for a quick meal.', 2, 23, '11/27/2024');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Grooming Supplies', 'Special attachment for vacuum cleaners to remove pet hair easily.', 1, 14, '9/28/2024');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Craft Kits', 'Complete crafting kit for kids and adults.', 2, 13, '8/13/2024');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Pet Feeding Supplies', 'Convenient feeder that adjusts to your pet''s height.', 2, 33, '12/25/2024');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Cooking Tools & Utensils', 'Complete set of cooking utensils made from bamboo.', 2, 22, '2/24/2025');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Healthy Snacks', 'Individually packaged bars made with dried fruits and nuts.', 5, 15, '1/5/2025');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Coffee Equipment', 'Unique coffee brewing method for a flavorful experience.', 1, 7, '10/28/2024');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Herbal Tea', 'A soothing tea blend with turmeric and ginger for wellness.', 3, 5, '6/16/2025');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Power Tools', 'Cordless electric screwdriver for home projects.', 5, 29, '3/21/2025');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Frozen Meals', 'Layers of pasta, veggies, and cheese baked to perfection.', 1, 6, '7/11/2024');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Dried Spices', 'Rich and sweet paprika spice for seasoning.', 5, 11, '11/21/2024');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Vegetable Snacks', 'Corn on the cob seasoned with chili and lime for a spicy kick.', 2, 19, '2/26/2025');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Jumpsuits', 'Chic wrap jumpsuit that flatters the body and is perfect for any occasion.', 1, 1, '2/6/2025');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Audio Accessories', 'Stream music from your device to any speaker wirelessly.', 4, 9, '11/21/2024');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Injury Prevention & Recovery', 'Rechargeable massage gun for relieving muscle soreness.', 2, 7, '9/9/2024');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Frozen Desserts', 'Seasonal pumpkin ice cream, perfect for fall.', 2, 12, '6/4/2025');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Leggings', 'Stylish faux leather leggings for a trendy outfit.', 1, 25, '11/16/2024');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Power Tools', 'Cordless electric screwdriver for home projects.', 3, 13, '5/10/2025');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Plant-Based Seasonings', 'Spice blend for creating flavorful vegan taco filling.', 2, 25, '8/8/2024');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Savory Nuts', 'Savory, roasted nuts seasoned with garlic and parmesan.', 5, 16, '6/9/2025');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Small Appliances', 'Make delicious waffles with this user-friendly device.', 1, 8, '2/15/2025');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Baking Ingredients', 'Sweet mixture of cinnamon and sugar for sprinkling.', 2, 16, '8/16/2024');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Camping Equipment', 'Lightweight hammock for easy setup anywhere.', 1, 12, '12/27/2024');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Noodles', 'Noodles tossed in a spicy Thai peanut sauce.', 2, 1, '6/7/2025');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Home Security', 'Wi-Fi camera with motion detection for home security.', 2, 30, '10/27/2024');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Gourmet Snacks', 'Popcorn tossed with sweet or savory flavors for a tasty snack.', 5, 18, '2/4/2025');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Bath & Body', 'Moisturizing body wash with natural ingredients.', 3, 7, '4/9/2025');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Air Quality & Purification', 'HEPA air purifier for clean indoor air.', 4, 17, '3/4/2025');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Pet Safety Gear', 'Safety vest for pets during nighttime walks.', 3, 13, '12/25/2024');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Furniture', 'Ergonomic desk that adjusts height for standing or sitting.', 1, 17, '9/21/2024');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Fruity Frozen Desserts', 'Refreshing sorbet with a zesty lemon flavor.', 4, 17, '12/22/2024');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Healthy Snacks', 'Light and crispy chips made from quinoa, ideal for dipping.', 2, 18, '5/22/2025');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Camping Equipment', 'Leak-proof cooler bag ideal for picnics and camping.', 4, 12, '12/2/2024');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Aromatherapy & Wellness', 'Set of roller bottles for blending and applying essential oils.', 4, 36, '4/25/2025');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Women''s Dress Shoes', 'Elegant classic pumps that add sophistication to any outfit.', 4, 26, '1/15/2025');
insert into Reviews (Title, [Description], Stars, MealId, CreatedDate) values ('Cooking Tools & Utensils', 'Fast and accurate thermometer for grilling and cooking.', 2, 31, '2/24/2025');
